"""Emitters that generate Python adapters.

LangChain, AutoGen and CrewAI do not consume a JSON description of a tool -- they
want Python objects: a pydantic model here, an annotated signature there, a
BaseTool subclass in the third. So for those three the output is source code.

The generated files are adapters, not implementations. Each leaves one obvious
hole where your function goes, and each carries the declared effects as a
comment at the top, so the warning that a tool destroys data survives into the
framework that has nowhere to put it.

Regenerating is meant to be routine: the header records the NTS digest, so a
diff shows immediately whether the interface moved or only the prose did.
"""

from __future__ import annotations

import keyword
import re
from typing import Any, List, Sequence, Tuple

from ..neutral import Param, ToolSchema

__all__ = ["to_langchain", "to_autogen", "to_crewai", "to_pydantic"]

Emitted = Tuple[str, List[str]]

_HEADER = (
    "# Generated by Attestry from the neutral tool schema for %r.\n"
    "# NTS interface digest: %s\n"
    "# Regenerate with: attestry schema emit %s --target %s\n"
    "# Declared effects: %s\n"
)


def _ident(name: str) -> str:
    """A safe Python identifier derived from a tool or parameter name."""
    cleaned = re.sub(r"[^0-9a-zA-Z_]", "_", name or "tool")
    if not cleaned or cleaned[0].isdigit():
        cleaned = "t_" + cleaned
    if keyword.iskeyword(cleaned):
        cleaned += "_"
    return cleaned


def _class_name(name: str) -> str:
    parts = [p for p in re.split(r"[^0-9a-zA-Z]+", name or "tool") if p]
    joined = "".join(p[:1].upper() + p[1:] for p in parts)
    return joined or "Tool"


def _annotation(param: Param) -> str:
    """The type annotation, widened to Optional when the value may be absent."""
    base = param.python_type()
    if param.required:
        return base
    if param.has_default and param.default is not None:
        return base
    return "Optional[%s]" % base


def _constraints(param: Param) -> List[str]:
    """pydantic Field constraints corresponding to the NTS bounds."""
    out = []
    if param.minimum is not None:
        out.append("ge=%r" % param.minimum)
    if param.maximum is not None:
        out.append("le=%r" % param.maximum)
    if param.min_length is not None:
        out.append("min_length=%r" % param.min_length)
    if param.max_length is not None:
        out.append("max_length=%r" % param.max_length)
    if param.min_items is not None:
        out.append("min_length=%r" % param.min_items)
    if param.max_items is not None:
        out.append("max_length=%r" % param.max_items)
    if param.pattern:
        out.append("pattern=%r" % param.pattern)
    return out


def _field_line(param: Param) -> str:
    if param.required:
        default_repr = "..."
    elif param.has_default:
        default_repr = repr(param.default)
    else:
        default_repr = "None"
    bits = [default_repr]
    if param.description:
        bits.append("description=%r" % param.description)
    bits.extend(_constraints(param))
    return "    %s: %s = Field(%s)" % (
        _ident(param.name),
        _annotation(param),
        ", ".join(bits),
    )


def _typing_imports(lines: Sequence[str], extra: Sequence[str] = ()) -> str:
    body = "\n".join(lines)
    needed = [name for name in ("Any", "Dict", "List", "Literal", "Optional")
              if re.search(r"\b%s\b" % name, body)]
    needed.extend(name for name in extra if name not in needed)
    if not needed:
        return ""
    return "from typing import %s\n" % ", ".join(sorted(set(needed)))


def _header(tool: ToolSchema, target: str) -> str:
    return _HEADER % (
        tool.name,
        tool.digest()[:16],
        tool.name + ".nts.json",
        target,
        tool.effects.summary(),
    )


def _args_model(tool: ToolSchema, suffix: str) -> Tuple[str, str, List[str]]:
    """Build a pydantic model for the arguments. Returns (name, source, notes)."""
    notes: List[str] = []
    class_name = _class_name(tool.name) + suffix
    field_lines = [_field_line(param) for param in tool.params]
    for param in tool.params:
        if _ident(param.name) != param.name:
            notes.append(
                "parameter %r is not a Python identifier and was emitted as %r; "
                "add a pydantic alias if the wire name must be preserved"
                % (param.name, _ident(param.name))
            )
        if param.type == "object" and param.properties:
            notes.append(
                "parameter %r is a nested object, emitted as Dict[str, Any]; "
                "the inner structure survives in the JSON targets only" % param.name
            )
    body = ["class %s(BaseModel):" % class_name]
    body.append("    %r" % (tool.description or tool.name))
    if field_lines:
        body.extend(field_lines)
    else:
        body.append("    pass")
    return class_name, "\n".join(body), notes


def to_pydantic(tool: ToolSchema, **options: Any) -> Emitted:
    """Just the argument model, for anything that speaks pydantic."""
    class_name, model, notes = _args_model(tool, "Args")
    lines = [model]
    source = (
        _header(tool, "pydantic")
        + "\nfrom __future__ import annotations\n\n"
        + _typing_imports(lines)
        + "from pydantic import BaseModel, Field\n\n\n"
        + model
        + "\n"
    )
    return source, notes


def to_langchain(tool: ToolSchema, **options: Any) -> Emitted:
    """A pydantic args schema plus a StructuredTool binding."""
    class_name, model, notes = _args_model(tool, "Args")
    func = _ident(tool.name)
    tail = [
        "def %s(**kwargs: Any) -> Any:" % func,
        "    %r" % (tool.description or tool.name),
        "    raise NotImplementedError(%r)" % (
            "implement %s, or pass func= your own callable" % func
        ),
        "",
        "",
        "%s_tool = StructuredTool.from_function(" % func,
        "    func=%s," % func,
        "    name=%r," % tool.name,
        "    description=%r," % tool.description,
        "    args_schema=%s," % class_name,
        ")",
    ]
    lines = [model] + tail
    source = (
        _header(tool, "langchain")
        + "\nfrom __future__ import annotations\n\n"
        + _typing_imports(lines, extra=["Any"])
        + "from langchain_core.tools import StructuredTool\n"
        + "from pydantic import BaseModel, Field\n\n\n"
        + model
        + "\n\n\n"
        + "\n".join(tail)
        + "\n"
    )
    if tool.consent.required:
        notes.append(
            "consent requirements do not survive into LangChain; wrap the "
            "callable with attestry.receipts.recorded() to keep the audit trail"
        )
    return source, notes


def to_autogen(tool: ToolSchema, **options: Any) -> Emitted:
    """An Annotated function signature, which is how AutoGen reads a tool.

    Parameters are reordered so required ones come first, because a Python
    signature cannot put a defaulted parameter before a bare one. The wire order
    is irrelevant to every target here -- arguments are passed by name -- but
    the reordering is reported anyway, since a reader comparing the adapter to
    the schema deserves to know why the list moved.
    """
    notes: List[str] = []
    required = [p for p in tool.params if p.required]
    optional = [p for p in tool.params if not p.required]
    if optional and required and tool.params != required + optional:
        notes.append(
            "reordered parameters so required ones come first, as a Python "
            "signature requires"
        )
    signature = []
    for param in required + optional:
        annotation = "Annotated[%s, %r]" % (param.python_type(), param.description)
        if param.required:
            signature.append("    %s: %s," % (_ident(param.name), annotation))
        else:
            default = repr(param.default) if param.has_default else "None"
            signature.append(
                "    %s: %s = %s," % (_ident(param.name), annotation, default)
            )
    func = _ident(tool.name)
    lines = ["def %s(" % func]
    lines.extend(signature)
    lines.append(") -> Any:")
    lines.append("    %r" % (tool.description or tool.name))
    lines.append("    raise NotImplementedError(%r)" % ("implement %s" % func))
    lines.extend(
        [
            "",
            "",
            "# Register with an AutoGen agent pair:",
            "#",
            "#     from autogen import register_function",
            "#     register_function(",
            "#         %s," % func,
            "#         caller=assistant,",
            "#         executor=user_proxy,",
            "#         name=%r," % tool.name,
            "#         description=%r," % tool.description,
            "#     )",
        ]
    )
    source = (
        _header(tool, "autogen")
        + "\nfrom __future__ import annotations\n\n"
        + _typing_imports(lines, extra=["Annotated", "Any"])
        + "\n"
        + "\n".join(lines)
        + "\n"
    )
    return source, notes


def to_crewai(tool: ToolSchema, **options: Any) -> Emitted:
    """A BaseTool subclass with a pydantic args_schema."""
    class_name, model, notes = _args_model(tool, "Input")
    tool_class = _class_name(tool.name) + "Tool"
    tail = [
        "class %s(BaseTool):" % tool_class,
        "    name: str = %r" % tool.name,
        "    description: str = %r" % (tool.description or tool.name),
        "    args_schema: Type[BaseModel] = %s" % class_name,
        "",
        "    def _run(self, **kwargs: Any) -> Any:",
        "        raise NotImplementedError(%r)" % ("implement %s._run" % tool_class),
    ]
    lines = [model] + tail
    source = (
        _header(tool, "crewai")
        + "\nfrom __future__ import annotations\n\n"
        + _typing_imports(lines, extra=["Any", "Type"])
        + "from crewai.tools import BaseTool\n"
        + "from pydantic import BaseModel, Field\n\n\n"
        + model
        + "\n\n\n"
        + "\n".join(tail)
        + "\n"
    )
    return source, notes
